<?php

return [
    'WANTED !!! Work in the SBA.' => 'WANTED!!! Работа в SBA.',
    'It\'s no secret that the corporate culture of our company goes far beyond the familiar faces. We can be really unpredictable, but it never affects the quality of our work.' => 'Ни для кого не секрет, что корпоративная культура нашей компании далеко выходит за привычные грани. Мы можем быть действительно непредсказуемыми, но это никогда не влияет на качество нашей работы.',
    'The company SBA - is a young team that is constantly growing and improving. It consists of employees age group 18-25 years. Due to the small difference in age, it turns out that we all speak the same language :). Of course, this is just one of the reasons that we are all easy to communicate and understand each other: we are pursuing the same goals, we have similar qualities - dedication, vividness, clarity of thought.' => 'Компания SBA – это молодой коллектив, который постоянно растет и совершенствуется. Он состоит из сотрудников возрастной категории 18-25 лет. За счёт небольшой разницы в возрасте, получается так, что мы все говорим на одном языке:). Конечно, это только одна из причин, по которой нам всем легко общаться и понимать друг друга: мы преследуем одинаковые цели, мы обладаем похожими качествами – целеустремленностью, живостью, ясностью мыслей.',
    'In view of the above stated, we are always in need of fresh blood and iron brains :). If you have never identifies himself with the above epithets - do not worry: shy, pragmatic leaders need us, too! :). The main thing that you need to learn - is the lack of our work any frameworks and conventions accepted stereotypes.' => 'Ввиду всего выше изложенного, мы всегда нуждаемся в свежей крови и железных мозгах:). Если Вы никогда не отожествляли себя с вышеперечисленными эпитетами – не огорчайтесь: застенчивые, прагматичные деятели нам тоже нужны!:). Главное, что Вы должны усвоить – это отсутствие в нашей работе каких-либо рамок и условностей, общепринятых стереотипов.',
    'It is also important to note that we select staff on the basis of - <strong><em>«First who, then what»</em></strong>. Which means, if you - a bright, extraordinary personality, which can bring into our company originality and creativity, we will first take you to work, and then come up with a post for you, or even open a department :). For us there are no obstacles on the way to the goal!' => 'Также важно отметить, что мы подбираем сотрудников по принципу – <strong><em>«сначала кто, потом что»</em></strong>. Что означает, если Вы - яркая, неординарная личность, которая может привнести в нашу компанию новизну и креативность, мы сначала примем Вас на работу, а потом придумаем для Вас должность, или даже откроем целый отдел:). Для нас не существует никаких преград на пути к достижению цели!',
    'The company SBA is working according to European standards, which we implement and in the internal policies of the company. For example, we got a job, you also get full freedom of action in the implementation of their tasks. For example, even in the second month of the company, when only three people worked in it, one of them, Vadim Belomar, (now the general manager), myself, at its discretion storudnikov picked up the rest. That is, the company shows you trust, and provides complete freedom of action in the implementation of tasks.' => 'Компания SBA работает по европейским стандартам, которые мы внедряем и во внутреннюю политику компании. Например, получив у нас работу, Вы также получаете полную свободу действий в реализации своих задач. Например, еще на втором месяце существования компании, когда в ней работало всего три человека, один из них, Вадим Беломар, (сейчас главный менеджер), сам, на свое усмотрение подбирал остальных сторудников. То есть, компания проявляет к вам доверие, а также предоставляет полную свободу действий в реализации заданий.',
    'We are not forbidden to make personal calls (in moderation, of course) or tea, is allocated for this time. But at the same time, each employee is mindful of its tasks, and is committed to its implementation, trying to maximize the end result and speed up time. And the last is not compulsory in our employees is laid on an intuitive level.' => 'У нас не возбраняется совершать личные звонки (в меру, конечно же) или пить чай, вне отведенного для этого времени. Но при этом, каждый сотрудник помнит о поставленной перед ним задаче, и стремится к ее реализации, стараясь максимально улучшить конечный результат и ускорить сроки. Причем последнее не является обязательным, в наших сотрудниках это заложено на интуитивном уровне.',
    'It should be noted that in view of the right to such freedom, our staff must possess an inner self-control and responsibility for all their actions, the desire to earn money and put it to all of your best efforts. During the immediate work no one is standing behind you or control you, but we regularly hold meetings and planning meetings at which each produces creative progress report, and shares his successes and failures. Can you come up with or create new approaches work, find new sources of useful information, to make a vivid idea of ​​the project - will receive an excellent bonus guaranteed.' => 'Следует отметить, что ввиду права на такую свободу, наш сотрудник должен обладать внутренним самоконтролем и ответственностью за все свои действия, желанием зарабатывать и прикладывать к этому все свои максимальные усилия. Во время выполнения непосредственной работы никто не стоит за вашей спиной и не контролирует вас, но мы регулярно проводим собрания и планерки, на которых каждый производит креативный отчет о проделанной работе, а также делится своими успехами и неудачами. Сможете придумать или создать новые подходы работы, найти новые полезные источники информации, внести яркую идею в проект – гарантировано получите отличную премию.',
    'If you really want to work in the SBA, but live in another city - it does not matter, because we - the International Agency Bukingovoe, and can work with you remotely. Besides, maybe tomorrow we will open a branch office is in your town!' => 'Если Вы очень хотите работать в SBA, но живете в другом городе – не беда, ведь мы - Международное Букинговое Агентство, и можем сотрудничать с Вами удаленно. К тому же, возможно уже завтра мы откроем офис-филиал именно в Вашем городе!',
    'In conclusion, I want to say that the pace of development of the company is growing every day, so every team member must also improve themselves and their skills on a daily basis. Immediately catches the eye, if someone behind or stopped - this employee can not work in the SBA. Each of us must strive for excellence in everything.' => 'В заключение, хочется сказать, что темп развития компании растет с каждым днем, поэтому каждый участник команды также должен совершенствовать себя и свои профессиональные навыки ежедневно. Сразу бросается в глаза, если кто-то отстал или остановился – такой сотрудник больше не может работать в SBA. Каждый из нас должен стремиться к совершенству во всем.',
    'The main selection criterion for us - to see it in your eyes desire to grow and earn. If you already have ideas for improving the company\'s work, useful information, or anything else interesting - always call or come to meet friends! Do not wait for a suitable job - Engage us, and we come up with the position of your dreams for you:)' => 'Главный критерий отбора для нас – это видеть в Ваших глазах желание развиваться и зарабатывать. Если у Вас уже есть идеи по улучшению работы компании, полезная информация или ещё что-нибудь интересное – обязательно звоните или приходите знакомиться! Не ждите подходящей вакансии – заинтересуйте нас, и мы придумаем должность Вашей мечты специально для Вас:)',
    'On this occasion, you can talk with the director of the SBA - Vadim Drozdovsky:' => 'По этому поводу можете пообщаться с директором компании SBA - Вадимом Дроздовским:',
];